# Generated by Django 4.1.7 on 2023-03-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True, primary_key=True, serialize=False,
                                     verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=3000, verbose_name='Описание')),
                ('status',
                 models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В процессе'), ('Done', 'Выполнена')],
                                  default='New', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateTimeField(null=True, verbose_name='Срок выполнения')),
            ],
        ),
    ]
